name: Deploy to Scalingo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install

      - name: Login to Scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}

      - name: Deploy to Scalingo
        run: git push scalingo main
